#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys

ans = [ float(formula) for formula in sys.stdin ]
ans=sum(ans)/len(ans)
if ans.is_integer():
    ans=int(ans)

file=open('ans_log.txt','a')
file.write('avg-> ')
file.write(str(ans)+'\n')
file.write('----------'+'\n')
print(ans)
