#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys

ans =[0]

for fomula in sys.stdin:
    normalize=str(fomula).split()
    ans+=normalize
print(ans)
