#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys

normalize =[0]

normalize=[ str(formula).split() for formula in sys.stdin ]
print(normalize)
