#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys
import re
import unicodedata

ans=[ re.findall(r'|\-+\d+\.+\d+|\-+\d+|\d+\.+\d+|\d+',unicodedata.normalize("NFKD",str(formula))) for formula in sys.stdin ]
ans=sum(ans,[])
for i in range(len(ans)):
    if ans[i] != "":
        print(ans[i])
