#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys

ans = [ float(formula) for formula in sys.stdin ]
ans=sum(ans)
if ans.is_integer():  #計算結果が整数値なら整数化
    ans=int(ans)

#結果を別ファイルへ記録
file=open('ans_log.txt','a')
file.write('sum-> ')
file.write(str(ans)+'\n')
file.write('----------'+'\n')
file.close()

print(ans)
