#!/usr/bin/python3
#SPDX-FileCopyrightText:2023 Shusuke Osawa hakuno0040@gmail.com
#SPDX-License-Identifier:BSD-3-Clause

import sys
import math

ans = [ float(formula) for formula in sys.stdin ]
ans=math.prod(ans)
if ans.is_integer():
    ans=int(ans)

print(ans)
